# 00_Pytorch_Foundation

## Import Pytorch

In [34]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)  # 检查版本
print(torch.cuda.is_available())  # 检查 CUDA 是否可用
print(torch.version.cuda) # 检查 CUDA 版本  

2.8.0+cu128
True
12.8


## Tensors

In [35]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [36]:
scalar.ndim

0

In [37]:
# Get tensor value as a standard Python number
scalar.item()

7

In [38]:
#Vector
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [39]:
vector.ndim

1

In [40]:
vector.shape    

torch.Size([3])

In [41]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [42]:
MATRIX.ndim

2

In [43]:
MATRIX[1]

tensor([ 9, 10])

In [44]:
MATRIX.shape 

torch.Size([2, 2])

## Random Tensors

In [45]:
# Creat a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5150, 0.4141, 0.5410, 0.8064],
        [0.7783, 0.8867, 0.8876, 0.6967],
        [0.7302, 0.0843, 0.1515, 0.6688]])

In [46]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size = (224, 224, 3)) #height, width, color channals (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [47]:
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
ones*random_tensor

tensor([[0.5150, 0.4141, 0.5410, 0.8064],
        [0.7783, 0.8867, 0.8876, 0.6967],
        [0.7302, 0.0843, 0.1515, 0.6688]])

In [51]:
ones.dtype

torch.float32

## Creating a Range of Tensors and Tensors-like

In [52]:
# Use torch.arange() to create a tensor of values between 1 and 10
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
one_to_twenty_with_step3 = torch.arange(start = 1, end = 21, step = 3)
one_to_twenty_with_step3

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [54]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes

#### **NOTE:** Three big errors might occur:

1. Tensors not right datatype;
2. Tensors not rigth shape;
3. Tensors not on the right devices;


In [55]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32,  # What data type is the tensor (e.g. float32, float64, int8, etc.)
                               device = "cuda", # What device is the tensor on (e.g. CPU, GPU)
                               requires_grad = False # Whether to track gradients for this tensor during backpropagation
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [56]:
float_32_tensor.dtype

torch.float32

In [57]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [58]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8346, 0.9210, 0.0199, 0.0638],
        [0.1073, 0.7000, 0.5219, 0.9018],
        [0.6178, 0.0630, 0.3304, 0.1656]])

In [59]:
#Find out the details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")
# Move tensor to GPU (if available)
if torch.cuda.is_available():
    some_tensor = some_tensor.to("cuda")
    print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.8346, 0.9210, 0.0199, 0.0638],
        [0.1073, 0.7000, 0.5219, 0.9018],
        [0.6178, 0.0630, 0.3304, 0.1656]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0


## Manipulating Tensors (tensor operations)

#### Tensor operations includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [60]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor_add10 = torch.add(tensor, 10)  # Add 10 to each element
print(tensor_add10)
tensor_mult10 = torch.mul(tensor, 10)  # Multiply each element by 10
print(tensor_mult10) 
tensor_sub10 = torch.sub(tensor, 10)  # Subtract 10 from each element
print(tensor_sub10)
tensor_div10 = torch.div(tensor, 10)  # Divide each element by 10
print(tensor_div10)
tensor_square = torch.pow(tensor, 2)  # Square each element
print(tensor_square)
tensor_mod2 = torch.remainder(tensor, 2)  # Modulus of each element
print(tensor_mod2)
tensor_floor_div2 = torch.floor_divide(tensor, 2)  # Floor division of each element
print(tensor_floor_div2)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 4, 9])
tensor([1, 0, 1])
tensor([0, 1, 1])


## Matrix multiplication

#### Two main ways of performing mulitiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [61]:
# Element wise multiplication
print(tensor, "*", tensor)  # Element-wise multiplication
print(f"Equals: {tensor * tensor}")

# Matrix multiplication
print(tensor.reshape(1, 3), "@" , tensor.reshape(3, 1))  # Matrix multiplication
print(f"Equals: {tensor.reshape(1, 3) @ tensor.reshape(3, 1)}") # Matrix multiplication using @ operator
print(f"Equals: {torch.matmul(tensor.reshape(1, 3), tensor.reshape(3, 1))}") # Matrix multiplication using torch.matmul

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor([[1, 2, 3]]) @ tensor([[1],
        [2],
        [3]])
Equals: tensor([[14]])
Equals: tensor([[14]])


In [62]:
# Reshape and transpose
print("tensor.reshape from (1, 3) to (3, 1) is equivalent to tensor.reshape(1, 3).T")
print("Original tensor:", tensor)
print(tensor.reshape(3, 1).reshape(1, 3))
print(tensor.reshape(3, 1).T)
print(tensor.T) # Note: 1D tensors do not have a transpose operation

tensor.reshape from (1, 3) to (3, 1) is equivalent to tensor.reshape(1, 3).T
Original tensor: tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1, 2, 3]])
tensor([1, 2, 3])


In [63]:
# Transpose a 2D tensor
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])   
print("2D Tensor:\n", tensor_2d)
print("Transposed 2D Tensor:\n", tensor_2d.T)

2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed 2D Tensor:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [65]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
# Find the maximum value
max_value1 = torch.max(x)
max_value2 = x.max()
max_value1, max_value2

(tensor(90), tensor(90))

In [68]:
# Find the minimum value
min_value1 = torch.min(x)
min_value2 = x.min()
min_value1, min_value2

(tensor(0), tensor(0))

In [70]:
# Find the mean value - note: the torch.mean() function requires a tensor of flot32 datatype to work
mean_value1 = torch.mean(x.type(torch.float32))
mean_value2 = x.type(torch.float32).mean()
mean_value1, mean_value2

(tensor(45.), tensor(45.))

In [71]:
# Find the sum
min_value1 = torch.sum(x)
min_value2 = x.sum()
min_value1, min_value2

(tensor(450), tensor(450))

## Finding the postional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the postion in tensor that has the minimum calue with argmin()
# -> return index position of target tensor where the minimum value is located
argmin_value = torch.argmin(x)
argmin_value

tensor(0)

In [74]:
# Find the postion in tensor that has the maximum calue with argmax()
# -> return index position of target tensor where the maximum value is located
argmax_value = torch.argmax(x)
argmax_value

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
y = torch.arange(1., 11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [106]:
# Add an extra dimension
y_reshaped = y.reshape(1, 10)  # Reshape to (1, 10)
y_reshaped, y_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [93]:
# Change the view
y_viewed = y.view(1, 10)  # View as (1, 10)
y_viewed, y_viewed.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [85]:
# Changing y_viewed changes y (because .view() returns a view of the original tensor)
y_viewed[:, 0] = 5
y_viewed, y

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim = 1)
y_stacked, y_stacked.shape, y

(tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]),
 torch.Size([10, 4]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [107]:
# Squeeze away single dimensions
print("Before squeeze:\n", y_reshaped)
print("Shape before squeeze:", y_reshaped.shape)
print("\n----------------------------------------\n")
y_squeezed = y_reshaped.squeeze()
print("After squeeze:\n", y_squeezed)
print("Shape after squeeze:", y_squeezed.shape)

Before squeeze:
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Shape before squeeze: torch.Size([1, 10])

----------------------------------------

After squeeze:
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Shape after squeeze: torch.Size([10])


In [109]:
# Unsqueeze the extra dimension
print("previous target:", y_squeezed)
print("previous shape:", y_squeezed.shape)
print("\n----------------------------------------\n")
y_unsqueezed = y_squeezed.unsqueeze(dim = 0)  # Add extra dimension at dim 0
print("After unsqueeze:\n", y_unsqueezed)
print("Shape after unsqueeze:", y_unsqueezed.shape)

previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
previous shape: torch.Size([10])

----------------------------------------

After unsqueeze:
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Shape after unsqueeze: torch.Size([1, 10])


In [ ]:
# Permute the dimensions of a tensor
image_tensor = torch.randn(3, 224, 224)  # Simulate an image tensor with (color channels, height, width)
print("Original image tensor shape:", image_tensor.shape)
permuted_image_tensor = image_tensor.permute(1, 2, 0)  # Change to (height, width, color channels)
print("Permuted image tensor shape:", permuted_image_tensor.shape)

Original image tensor shape: torch.Size([3, 224, 224])
Permuted image tensor shape: torch.Size([224, 224, 3])


## Indexing (Selecting data from tensors)

Indexing with PyTorch is similiar to indexing with Numpy.