# 00_Pytorch_Foundation

## Import Pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)  # 检查版本
print(torch.cuda.is_available())  # 检查 CUDA 是否可用
print(torch.version.cuda) # 检查 CUDA 版本  

2.8.0+cu128
True
12.8


## Introduce to tensors

### Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor value as a standard Python number
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape    

torch.Size([3])

In [8]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape 

torch.Size([2, 2])

### Random Tensors

In [12]:
# Creat a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5123, 0.8144, 0.9107, 0.2888],
        [0.4800, 0.0609, 0.0917, 0.5314],
        [0.1326, 0.2739, 0.1081, 0.8775]])

In [13]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size = (224, 224, 3)) #height, width, color channals (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [14]:
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones*random_tensor

tensor([[0.5123, 0.8144, 0.9107, 0.2888],
        [0.4800, 0.0609, 0.0917, 0.5314],
        [0.1326, 0.2739, 0.1081, 0.8775]])

In [18]:
ones.dtype

torch.float32

### Creating a Range of Tensors and Tensors-like

In [19]:
# Use torch.arange() to create a tensor of values between 1 and 10
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
one_to_twenty_with_step3 = torch.arange(start = 1, end = 21, step = 3)
one_to_twenty_with_step3

tensor([ 1,  4,  7, 10, 13, 16, 19])

In [21]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes

 **NOTE:** Three big errors might occur:

1. Tensors not right datatype;
2. Tensors not rigth shape;
3. Tensors not on the right devices;


In [22]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32,  # What data type is the tensor (e.g. float32, float64, int8, etc.)
                               device = "cuda", # What device is the tensor on (e.g. CPU, GPU)
                               requires_grad = False # Whether to track gradients for this tensor during backpropagation
                               )
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3284, 0.1276, 0.2035, 0.3543],
        [0.5058, 0.2929, 0.0875, 0.2119],
        [0.7536, 0.9646, 0.5117, 0.2611]])

In [26]:
#Find out the details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")
# Move tensor to GPU (if available)
if torch.cuda.is_available():
    some_tensor = some_tensor.to("cuda")
    print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.3284, 0.1276, 0.2035, 0.3543],
        [0.5058, 0.2929, 0.0875, 0.2119],
        [0.7536, 0.9646, 0.5117, 0.2611]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0


## Manipulating Tensors (tensor operations)

Tensor operations includes:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

### Foudamental Operations

In [27]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor_add10 = torch.add(tensor, 10)  # Add 10 to each element
print(tensor_add10)
tensor_mult10 = torch.mul(tensor, 10)  # Multiply each element by 10
print(tensor_mult10) 
tensor_sub10 = torch.sub(tensor, 10)  # Subtract 10 from each element
print(tensor_sub10)
tensor_div10 = torch.div(tensor, 10)  # Divide each element by 10
print(tensor_div10)
tensor_square = torch.pow(tensor, 2)  # Square each element
print(tensor_square)
tensor_mod2 = torch.remainder(tensor, 2)  # Modulus of each element
print(tensor_mod2)
tensor_floor_div2 = torch.floor_divide(tensor, 2)  # Floor division of each element
print(tensor_floor_div2)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 4, 9])
tensor([1, 0, 1])
tensor([0, 1, 1])


### Matrix multiplication

Two main ways of performing mulitiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [28]:
# Element wise multiplication
print(tensor, "*", tensor)  # Element-wise multiplication
print(f"Equals: {tensor * tensor}")

# Matrix multiplication
print(tensor.reshape(1, 3), "@" , tensor.reshape(3, 1))  # Matrix multiplication
print(f"Equals: {tensor.reshape(1, 3) @ tensor.reshape(3, 1)}") # Matrix multiplication using @ operator
print(f"Equals: {torch.matmul(tensor.reshape(1, 3), tensor.reshape(3, 1))}") # Matrix multiplication using torch.matmul

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor([[1, 2, 3]]) @ tensor([[1],
        [2],
        [3]])
Equals: tensor([[14]])
Equals: tensor([[14]])


In [29]:
# Reshape and transpose
print("tensor.reshape from (1, 3) to (3, 1) is equivalent to tensor.reshape(1, 3).T")
print("Original tensor:", tensor)
print(tensor.reshape(3, 1).reshape(1, 3))
print(tensor.reshape(3, 1).T)
print(tensor.T) # Note: 1D tensors do not have a transpose operation

tensor.reshape from (1, 3) to (3, 1) is equivalent to tensor.reshape(1, 3).T
Original tensor: tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1, 2, 3]])
tensor([1, 2, 3])


C:\Users\ROG\AppData\Local\Temp\ipykernel_22728\289585187.py:6: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4424.)
  print(tensor.T) # Note: 1D tensors do not have a transpose operation


In [30]:
# Transpose a 2D tensor
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])   
print("2D Tensor:\n", tensor_2d)
print("Transposed 2D Tensor:\n", tensor_2d.T)

2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed 2D Tensor:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [31]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
# Find the maximum value
max_value1 = torch.max(x)
max_value2 = x.max()
max_value1, max_value2

(tensor(90), tensor(90))

In [33]:
# Find the minimum value
min_value1 = torch.min(x)
min_value2 = x.min()
min_value1, min_value2

(tensor(0), tensor(0))

In [34]:
# Find the mean value - note: the torch.mean() function requires a tensor of flot32 datatype to work
mean_value1 = torch.mean(x.type(torch.float32))
mean_value2 = x.type(torch.float32).mean()
mean_value1, mean_value2

(tensor(45.), tensor(45.))

In [35]:
# Find the sum
min_value1 = torch.sum(x)
min_value2 = x.sum()
min_value1, min_value2

(tensor(450), tensor(450))

## Finding the postional min and max

In [36]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
# Find the postion in tensor that has the minimum calue with argmin()
# -> return index position of target tensor where the minimum value is located
argmin_value = torch.argmin(x)
argmin_value

tensor(0)

In [38]:
# Find the postion in tensor that has the maximum calue with argmax()
# -> return index position of target tensor where the maximum value is located
argmax_value = torch.argmax(x)
argmax_value

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [39]:
# Create a tensor
y = torch.arange(1., 11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [40]:
# Add an extra dimension
y_reshaped = y.reshape(1, 10)  # Reshape to (1, 10)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [41]:
# Change the view
y_viewed = y.view(1, 10)  # View as (1, 10)
y_viewed, y_viewed.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [42]:
# Changing y_viewed changes y (because .view() returns a view of the original tensor)
y_viewed[:, 0] = 5
y_viewed, y

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [43]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim = 1)
y_stacked, y_stacked.shape, y

(tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]),
 torch.Size([10, 4]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [44]:
# Squeeze away single dimensions
print("Before squeeze:\n", y_reshaped)
print("Shape before squeeze:", y_reshaped.shape)
print("\n----------------------------------------\n")
y_squeezed = y_reshaped.squeeze()
print("After squeeze:\n", y_squeezed)
print("Shape after squeeze:", y_squeezed.shape)

Before squeeze:
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Shape before squeeze: torch.Size([1, 10])

----------------------------------------

After squeeze:
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Shape after squeeze: torch.Size([10])


In [45]:
# Unsqueeze the extra dimension
print("previous target:", y_squeezed)
print("previous shape:", y_squeezed.shape)
print("\n----------------------------------------\n")
y_unsqueezed = y_squeezed.unsqueeze(dim = 0)  # Add extra dimension at dim 0
print("After unsqueeze:\n", y_unsqueezed)
print("Shape after unsqueeze:", y_unsqueezed.shape)

previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
previous shape: torch.Size([10])

----------------------------------------

After unsqueeze:
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Shape after unsqueeze: torch.Size([1, 10])


In [46]:
# Permute the dimensions of a tensor
image_tensor = torch.randn(3, 224, 224)  # Simulate an image tensor with (color channels, height, width)
print("Original image tensor shape:", image_tensor.shape)
permuted_image_tensor = image_tensor.permute(1, 2, 0)  # Change to (height, width, color channels)
print("Permuted image tensor shape:", permuted_image_tensor.shape)

Original image tensor shape: torch.Size([3, 224, 224])
Permuted image tensor shape: torch.Size([224, 224, 3])


## Indexing (Selecting data from tensors)

Indexing with PyTorch is similiar to indexing with Numpy.

In [47]:
# Create a tensor
z = torch.arange(1, 10).reshape(1, 3, 3)
z, z.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
# Indexing on our new tensor
z[0]  # Get the first (and only) 2D matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
# Indexing on the middle bracket (dim = 1)
z[0][0]

tensor([1, 2, 3])

In [50]:
# Indexing on the most inner bracket (dim = 2)
z[0][0][0]

tensor(1)

In [51]:
# Using ":" to select all values along a dimension
z[:, 0]  # Get all matrices' first row

tensor([[1, 2, 3]])

In [52]:
z[:, :, 2]  # Get all matrices' third column

tensor([[3, 6, 9]])

In [53]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
z[0, 0, :]

tensor([1, 2, 3])

In [54]:
# Index on x to return 9
print(z[0, 2, 2])

# Index on x to return 3, 6, 9
print(z[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [55]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor_from_array = torch.from_numpy(array)
array, tensor_from_array

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [56]:
# The dtype of the NumPy array and tensor are different
tensor_from_pytorch = torch.arange(1.0, 8.0)
array.dtype, tensor_from_pytorch.dtype

(dtype('float64'), torch.float32)

In [57]:
# Change the value of array, what happens to the tensor?
array += 1
array, tensor_from_array

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [58]:
# Tensor to NumPy array
tensor_for_numpy = torch.ones(7)
numpy_from_tensor = tensor_for_numpy.numpy()
tensor_for_numpy, numpy_from_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [59]:
# Change the value of the tensor, what happens to the NumPy array?
tensor_for_numpy += 1
tensor_for_numpy, numpy_from_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers` -> `tensor operations` -> `update random numbers to try and make them of the data` -> `again` -> `again` -> ...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [60]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A, random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5794, 0.2516, 0.5128, 0.6839],
        [0.0712, 0.0093, 0.1399, 0.3657],
        [0.1778, 0.0019, 0.1277, 0.9030]]) tensor([[0.2153, 0.5839, 0.4821, 0.5560],
        [0.2633, 0.2924, 0.0196, 0.5734],
        [0.9972, 0.5800, 0.4926, 0.8857]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
# Make some random but reproducible tensors
def set_seed(seed = 42):
    torch.manual_seed(seed)
    np.random.seed(seed)
    import random
    random.seed(seed)
set_seed()  # Set the seed for reproducibility
random_tensor_C = torch.rand(3, 4)
print(random_tensor_C)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [62]:
# To make these two the same - we need to reset the seed every time we want the same random numbers
set_seed()  # Reset the seed to the same value
random_tensor_D = torch.rand(3, 4) 
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

In [63]:
# Check for GPU access with PyTorch
if torch.cuda.is_available():
    print("GPU is available")
    device = torch.device("cuda")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
    device_number = torch.cuda.device_count()
    print(f"Number of available GPUs: {device_number}") 
else:
    print("GPU not available, using CPU instead")
    device = torch.device("cpu")
    

GPU is available
Device name: NVIDIA GeForce RTX 4070 Laptop GPU
Number of available GPUs: 1
